---
kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive

- name: build-centos-6
  image: obsrvbl/docker-images:suricata-centos-6.10
  commands:
  - source /root/.cargo/env
  - yum install lz4-devel
  - LC_ALL="en_US.utf8" LANG="en_US.utf8" make build_suricata rpm6

- name: build-centos-7
  image: obsrvbl/docker-images:suricata-centos-7.7
  environment:
    LC_ALL: en_US.utf8
    LANG: en_US.utf8
  commands:
  - yum install lz4-devel
  - LC_ALL="en_US.utf8" LANG="en_US.utf8" make build_suricata rpm7

- name: build-ubuntu-16.04
  image: obsrvbl/docker-images:suricata-ubuntu-16.04
  commands:
  - apt-get install liblz4-dev
  - make build_suricata deb

- name: publish
  image: plugins/s3
  settings:
    region: us-east-1
    acl: public-read
    source: packaging/output/*
    strip_prefix: packaging/output/
    bucket: onstatic
    target: suricata-service/${DRONE_BRANCH}/
  when:
    event: push
