pipeline:
  build:
    image: obsrvbl/docker-images:suricata-${SURICATA_IMAGE}
    environment:
      - LC_ALL=en-us.UTF-8
      - LANG=en-us.UTF-8
    commands:
      - make build_suricata
      - if [ ${SURICATA_IMAGE} = "centos-6" ]; then make rpm6; elif [ ${SURICATA_IMAGE} = "centos-7" ]; then make rpm7; else make deb; fi
      - pip install awscli
      - aws s3 cp --region us-east-1 --recursive --acl public-read packaging/output/ s3://onstatic/suricata-service/${DRONE_BRANCH}/

matrix:
  SURICATA_IMAGE:
    - centos-7
    - centos-6
    - ubuntu-14.04
