---
kind: pipeline
name: default

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive

- name: build-ubuntu-16.04
  image: obsrvbl/docker-images:suricata-ubuntu-16.04
  environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  commands:
  - make build_suricata
  - make deb

- name: build-centos-7.7
  image: obsrvbl/docker-images:suricata-centos-7
  pull: always
  environment:
    LC_ALL: en_US.utf8
    LANG: en_US.utf8
  commands:
  - make build_suricata
  - make rpm7

- name: build-centos-6
  image: obsrvbl/docker-images:suricata-centos-6
  pull: always
  environment:
    LC_ALL: en_US.utf8
    LANG: en_US.utf8
  commands:
  - make build_suricata
  - make rpm6

- name: publish
  image: plugins/s3
  settings:
    region: us-east-1
    acl: public-read
    source: packaging/output/*
    strip_prefix: packaging/output/
    bucket: onstatic
    target: suricata-service/${DRONE_BRANCH}/
  when:
    event: push
