env:
  - AWS_ACCESS_KEY_ID=$$AWS_KEY
  - AWS_SECRET_ACCESS_KEY=$$AWS_SECRET
  - AWS_DEFAULT_REGION=us-east-1

build:
  image: obsrvbl/suricata-$$SURICATA_IMAGE:latest
  commands:
    - git submodule update --init --recursive
    - make build_suricata
    - if [ $$SURICATA_IMAGE = "centos-6" ]; then make rpm; else make deb; fi
    - pip install awscli
    - aws s3 cp "packaging/output" "s3://onstatic/suricata-service/$DRONE_BRANCH/" --recursive --acl="public-read"

matrix:
  SURICATA_IMAGE:
    - centos-6
    - ubuntu-trusty

notify:
  email:
    recipients:
      - engineering@obsrvbl.com
