build:
  image: obsrvbl/suricata-$$SURICATA_IMAGE
  commands:
    - git submodule update --init --recursive
    - make build_suricata
    - make rpm
    - make deb

matrix:
  SURICATA_IMAGE:
    - centos-6
    - ubuntu-trusty

notify:
  email:
    recipients:
      - engineering@obsrvbl.com

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: onstatic
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: packaging/output
    target: suricata-service/$DRONE_BRANCH/
    recursive: true
    when:
      owner: obsrvbl
