pipeline:
  submodules:
    image: docker:git
    commands:
      - git submodule update --recursive --remote

  build:
    image: obsrvbl/docker-images:suricata-${SURICATA_IMAGE}
    environment:
      - LC_ALL=${ENV_LC_ALL}
      - LANG=${ENV_LANG}
    commands:
      - make build_suricata
      - if [ ${SURICATA_IMAGE} = "centos-6" ]; then make rpm6; elif [ ${SURICATA_IMAGE} = "centos-7" ]; then make rpm7; else make deb; fi
      - pip install awscli
      - aws s3 cp --region us-east-1 --recursive --acl public-read packaging/output/ s3://onstatic/suricata-service/${DRONE_BRANCH}/
    when:
      event: push

matrix:
  include:
    - SURICATA_IMAGE: ubuntu-14.04
      ENV_LC_ALL: C.UTF-8
      ENV_LANG: C.UTF-8
    - SURICATA_IMAGE: centos-6
      ENV_LC_ALL: en_US.utf8
      ENV_LANG: en_US.utf8
    - SURICATA_IMAGE: centos-7
      ENV_LC_ALL: en_US.utf8
      ENV_LANG: en_US.utf8
