build:
  image: obsrvbl/suricata-$$SURICATA_IMAGE:latest
  environment:
    - AWS_DEFAULT_REGION=us-east-1
  commands:
    - git submodule update --init --recursive
    - make build_suricata
    - if [ $$SURICATA_IMAGE = "centos-6" ]; then make rpm; else make deb; fi
    - pip install awscli
    - env
    - aws s3 cp "packaging/output" "s3://onstatic/suricata-service/$DRONE_BRANCH/" --recursive --acl="public-read"

matrix:
  SURICATA_IMAGE:
    - centos-6
    - ubuntu-trusty

notify:
  email:
    recipients:
      - engineering@obsrvbl.com
