name: suricata-service CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build_ubuntu:
    name: Build Ubuntu 16.04
    runs-on: ubuntu-latest
    container: obsrvbl/docker-images:suricata-ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build .deb package
        run: make build_suricata deb
